version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  backend:
    image: backend
    depends_on:
      - mongodb
    build:
      context: ./DotaMaster      
      dockerfile: Dockerfile
    container_name: dotamaster-backend
    ports:
      - "5226:80" 
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  frontend:
    image: frontend
    depends_on:
      - mongodb
      - backend
    build:
      context: .
      dockerfile: .dota-master-client/Dockerfile
    environment:
      NODE_ENV: production
      VITE_PUBLIC_BACKEND_DOMAIN: http://localhost:5226
      VITE_PUBLIC_HERO_PORTRAITS_DOMAIN: https://cdn.dota2.com/apps/dota2/images/dota_react/heroes
      VITE_PUBLIC_ITEM_ICONS_DOMAIN: https://cdn.dota2.com
      VITE_PUBLIC_HERO_ICONS_DOMAIN: https://cdn.stratz.com/images/dota2/heroes
      VITE_MATCHES_LIMIT_SIZE: 15
    ports:
      - 3000:3000