services:
  dotamaster.api:
    image: ${DOCKER_REGISTRY-}dotamasterapi
    depends_on:
      - mongodb
    ports:
      - "5226:8080"
    build:
      context: .
      dockerfile: DotaMaster.API/Dockerfile

  frontend:
    build:
      context: ../dota-master-client
      dockerfile: dockerfile
    container_name: dotamaster-frontend
    depends_on:
      - mongodb
      - dotamaster.api
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      VITE_PUBLIC_BACKEND_DOMAIN: http://localhost:5226
      VITE_DOCKER_BACKEND_DOMAIN: http://localhost:5226
      VITE_PUBLIC_HERO_PORTRAITS_DOMAIN: https://cdn.dota2.com/apps/dota2/images/dota_react/heroes
      VITE_PUBLIC_ITEM_ICONS_DOMAIN: https://cdn.dota2.com
      VITE_PUBLIC_HERO_ICONS_DOMAIN: https://cdn.stratz.com/images/dota2/heroes
      VITE_MATCHES_LIMIT_SIZE: 15

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123