FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app 

COPY *.sln .
COPY DotaMaster.API/*.csproj ./DotaMaster.API/
COPY DotaMaster.Application/*.csproj ./DotaMaster.Application/
COPY DotaMaster.Data/*.csproj ./DotaMaster.Data/
COPY DotaMaster.Domain/*.csproj ./DotaMaster.Domain/ 

RUN dotnet restore 

COPY DotaMaster.API/. ./DotaMaster.API/
COPY DotaMaster.Application/. ./DotaMaster.Application/
COPY DotaMaster.Data/. ./DotaMaster.Data/ 
COPY DotaMaster.Domain/. ./DotaMaster.Domain/ 

WORKDIR /app/DotaMaster.API
RUN dotnet publish -c Release -o out 

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app 

COPY --from=build /app/DotaMaster.API/out ./
ENTRYPOINT ["dotnet", "DotaMaster.API.dll"]